SELECT * FROM PARTICIPATED ORDER BY DAMAGE_AMT DESC;

SELECT AVG(DAMAGE_AMT) FROM PARTICIPATED;

DELETE FROM PARTICIPATED WHERE DAMAGE_AMT < (SELECT AVG(DAMAGE_AMT) FROM PARTICIPATED);

SELECT NAME FROM PERSON A, PARTICIPATED B WHERE A.DRIVER_ID = B.DRIVER_ID AND DAMAGE_AMT>(SELECT AVG(DAMAGE_AMT) FROM PARTICIPATED);

SELECT MAX(DAMAGE_AMT) FROM PARTICIPATED;

select*
from car
order by year asc;

select count(report_num)
from car c, participated p
where c.reg_num=p.reg_num and c.model='Lancer';
